--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adamMCBE/GuildShopping
branches:
- master
projects:
  GuildShopping:
    path: ""
    libs:
      - src: "vkamz597/ItemParser/ItemParser"
        branch: "api/5"
        version: ^5.0.0
...
